export type EvidenceStatus = "observed" | "derived" | "simulated" | "scenario";

export const studyFacts = {
  title: "Motorcyclist Hazard Perception and Situational Awareness Deficits",
  subtitle: "Evidence for Motorcycle Collision Warning Technologies and Policy Reform in Malaysia",
  experiment1: { n: 31, mrtt: 68.1, hpt: 49.3, knowledge: 54.5 },
  experiment2: {
    n: 264,
    totalSA: 23.2,
    level1: 27.5,
    youngerN: 184,
    youngerSA: 17.9,
    olderN: 79,
    olderSA: 35.3,
    t: 5.93,
    p: "<.001",
    ageR: 0.40,
    partialAgeR: 0.39,
    exposureR: 0.13
  },
  anova: { F: 14.74, df1: 1.66, df2: 49.71, p: "<.0001", eta2: 0.19 },
  framework: ["Pre-licensing", "Licensing", "Technology", "Exposure control", "Retraining"]
};

export const evidenceLegend = [
  { key: "observed" as EvidenceStatus, label: "Observed", note: "Directly reported in the published study." },
  { key: "derived" as EvidenceStatus, label: "Derived", note: "Calculated from reported study quantities." },
  { key: "simulated" as EvidenceStatus, label: "Simulated", note: "Synthetic results generated by this Explorer." },
  { key: "scenario" as EvidenceStatus, label: "Scenario", note: "User-defined intervention assumptions; not an empirical finding." }
];

export const provenance = [
  { id: "e1", title: "Experiment 1", status: "observed" as EvidenceStatus, detail: "31 courier riders; MRRT, HPT and knowledge assessment." },
  { id: "e2", title: "Experiment 2", status: "observed" as EvidenceStatus, detail: "264 motorcyclists; video-based MRSAA/SAGAT assessment." },
  { id: "m1", title: "HPT stimulus", status: "observed" as EvidenceStatus, detail: "12 video clips containing 31 real-road motorcycle hazards." },
  { id: "m2", title: "MRSAA stimulus", status: "observed" as EvidenceStatus, detail: "Rider-perspective video clips with freeze-frame questions across three SA levels." },
  { id: "f1", title: "IMSEF-MY", status: "observed" as EvidenceStatus, detail: "Five action domains proposed by the paper: pre-licensing, licensing, technology, exposure control and retraining." },
  { id: "s1", title: "Monte Carlo Lab", status: "simulated" as EvidenceStatus, detail: "Synthetic studies generated from explicit assumptions selected by the reader." }
];
